### ISSUE TITLE
In rooms.json adjacentRoom is incorrect

### ISSUE THREAD

**Issue by kevindeslauriers** [wmacinnisBVG/Simpsons#1]
The rooms.json file must ensure that the adjacentRoom field references the if of the room and not the room name. adjacentRoom should not be Entryway but a room id.

{
      "id": "Main-House-Kitchen",
      "name": "Entryway",
      "description": "The kitchen of the Simpsons house.",
      "exits": [
        {
          "isLocked": false,
          "direction": "North",
          "adjacentRoom": "Backyard"
        },
        {
          "isLocked": false,
          "direction": "South",
          "adjacentRoom": "_**Entryway**_"
        },
        {
          "isLocked": false,
          "direction": "West",
          "adjacentRoom": "TV Room"
        }
        ]
    }

**Comment by haydenkan** [comment]
Fixed myself because William is not here today.
